### ISSUE TITLE
optimize just hangs

### ISSUE THREAD

**Issue by ironside** [sjrd/scala-js-example-app#4]
sbt 0.13.6

Following the readme directions,  I run sbt, then run fastOptJS it just hangs at:

`[info] Fast optimizing /media/shawn/Toshiba1TB/scalaStuff/clone/target/scala-2.11/example-fastopt.js`

I waited several minutes for it to complete; I certainly hope this isn't the expected experience for getting started with ScalaJS :)

**Comment by sjrd** [comment]
It is not expected, no. 
Did you actually change `project/build.properties` to say 0.13.6? I realize now that I forgot to update that bit of this repo, and sbt < 0.13.6 can hang optimize on a JDK 8.

**Comment by sjrd** [comment]
I have updated master to reference sbt 0.13.7. Does this fix your issue?

**Comment by ironside** [comment]
Unfortunately it did not. I actually had 0.13.6 at first (with JDK7). Tried updating to sbt 0.13.7 then also JDK8 all with no luck.... only then did I file the ticket...

For comparison, lihaoyi's example app seems to fastOptJS without error ( https://github.com/lihaoyi/workbench-example-app ).

**Comment by sjrd** [comment]
OK that's worrying :-s This is definitely a new bug, then. I've never heard of it. I can't reproduce it either, I just tested when I updated with sbt 0.13.7.

lihaoyi's example uses 0.5.5, this one uses 0.5.6. Maybe try downgrading (in `project/build.sbt`). Or, possibly better, try 0.6.0-M3 by cloning [this branch](https://github.com/sjrd/scala-js-example-app/tree/upgrade-to-0.6.0-M3)?

**Comment by ironside** [comment]
So sorry, I spoke too soon (quickly ran the app on a clone that wasn't up to date)....

Yes, the sbt bump to 0.13.7 now builds!

Much thanks.

**Comment by sjrd** [comment]
Oh OK great, thanks for your feedback :-)
