### ISSUE TITLE
/target/scala-2.11/example-launcher.js is missing

### ISSUE THREAD

**Issue by SebastianMetzger** [sjrd/scala-js-example-app#7]
I tried this example app out and /target/scala-2.11/example-launcher.js is somehow missing, so the app won't launch.
Am I missing something?

**Comment by sjrd** [comment]
Did you run `fastOptJS` in `sbt`?

**Comment by SebastianMetzger** [comment]
Ah, now I got it, had a typo in my command, I always ran 'sbt fullOptJS'

Nevermind! ;)

Thanks for this example project!
